# Generated by Django 4.1 on 2022-08-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clone',
            name='eld_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
