# Generated by Django 4.1.7 on 2023-03-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_editload_carrier_alter_load_carrier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="edittrailer",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="edittrailer",
            name="note",
        ),
        migrations.RemoveField(
            model_name="trailer",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="trailer",
            name="note",
        ),
        migrations.AddField(
            model_name="edittrailer",
            name="status",
            field=models.CharField(
                choices=[("ius", "In use"), ("uns", "Unused"), ("rep", "Repairing")],
                default="uns",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="trailer",
            name="status",
            field=models.CharField(
                choices=[("ius", "In use"), ("uns", "Unused"), ("rep", "Repairing")],
                default="uns",
                max_length=3,
            ),
        ),
    ]
